name: ReachUp
description: Mobile application for indoor location, provides blind and visually impaired an interaction experience in the mall, using voice tools the users can search by stores, bathrooms, restaurants and so on. Besides that, the application offers tools for shopkeepers publish their promotions or communicated and mall managers receive a user visit reports by the mall.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.3
  mobx: ^2.2.0
  flutter_mobx: ^2.1.0
  provider: ^6.0.0
  font_awesome_flutter: ^9.0.0
  flutter_beacon: ^0.5.1

  path_provider:
  photo_view: 0.14.0
  flutter_image_compress: ^2.1.0
  path:

  flutter_tts: ^3.8.3
  ## Dart 3 incompatible
  #sensors: ^0.4.2+5
  sensors_plus: ^3.1.0
  flutter_compass: ^0.8.0
  gesture_x_detector: 1.1.1

  lottie: ^2.7.0

  cupertino_icons: 1.0.6
  http: ^1.1.0
  giffy_dialog:
  flutter_signin_button: 2.0.0
  ## Dart 3 incompatible
  #fa_stepper: ^0.0.2
  async: ^2.4.2
  flutter_easyloading: ^3.0.5
  cached_network_image: ^3.3.0
  ## Dart 3 incompatible
  #flutter_circular_chart: ^0.1.0
  circular_chart_flutter: 0.0.2
  intl: 0.18.1
  flutter_rating_bar: 4.0.1
  toggle_switch: ^2.1.0
  flutter_slidable: 3.0.0
  get_storage: 2.1.1
  get:

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0
  flutter_launcher_icons: ^0.13.1
 
flutter:
  assets:
    #Animations
    - assets/animations/user-location.json
    - assets/animations/pin-pointer.json
    - assets/animations/search.json
    - assets/animations/pin.json

    #Images
    - assets/images/map/floor0.jpg
    - assets/images/map/floor1.jpg
    - assets/images/bkg/bkg_initial_screen.jpg

    - assets/images/icons/widgets/user-location.png
    - assets/images/icons/launch/ReachUp.png

    #Config
    - assets/config/global/config-global.json
    - assets/map/map.json


  uses-material-design: true
